"""initial migrate

Revision ID: 40e51195b3fb
Revises: 
Create Date: 2023-09-19 22:07:45.707461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e51195b3fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('fisrt_name', sa.String(length=128), nullable=False),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.CHAR(), nullable=True),
    sa.Column('state_of_origin', sa.String(length=64), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('nok_fullname', sa.String(length=128), nullable=True),
    sa.Column('nok_address', sa.String(length=128), nullable=True),
    sa.Column('nok_number', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
