"""USER: mistake on first_name field spelling

Revision ID: 70afbe49f635
Revises: a4e9af45c35b
Create Date: 2023-09-21 00:36:37.644358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70afbe49f635'
down_revision = 'a4e9af45c35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=128), nullable=True))
        batch_op.drop_column('fisrt_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fisrt_name', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
