"""USER: removed all nullables for Admin creation sake

Revision ID: 7da34dda0d96
Revises: 6fe7af4ed2f0
Create Date: 2023-09-22 16:36:46.459923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da34dda0d96'
down_revision = '6fe7af4ed2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ready', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('course',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('course',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('id_ready')

    # ### end Alembic commands ###
