"""USER: added a rusticated field

Revision ID: 863ff6a49fde
Revises: 98c3bc4b8ffc
Create Date: 2023-09-27 22:02:06.077936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863ff6a49fde'
down_revision = '98c3bc4b8ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rusticated', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rusticated')

    # ### end Alembic commands ###
