"""USER: added field to show student ID validity and status

Revision ID: 98c3bc4b8ffc
Revises: 7da34dda0d96
Create Date: 2023-09-27 21:43:42.257369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c3bc4b8ffc'
down_revision = '7da34dda0d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_status', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('id_status')

    # ### end Alembic commands ###
