"""USER: removed null constraints and added department field

Revision ID: a4e9af45c35b
Revises: 40e51195b3fb
Create Date: 2023-09-21 00:26:31.199284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e9af45c35b'
down_revision = '40e51195b3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=64), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('fisrt_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('fisrt_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('department')

    # ### end Alembic commands ###
